# Generated by Django 3.1.3 on 2020-11-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('symbol', models.CharField(max_length=10)),
                ('aimed_price', models.FloatField()),
                ('current_price', models.FloatField()),
                ('user_id', models.FloatField()),
            ],
        ),
    ]
